func_cache:
  func_use_cache: true
  func_cache_ttl: 43203
  func_max_cache_entry: 10000
hie_cache:
  hie_use_cache: true
  hie_cache_ttl: 43202
  hie_max_cache_entry: 10000
datasource:
  - drive_name: mysql
    name: abac
    url: root:123456@tcp(localhost:3306)/abac
  - drive_name: mysql
    name: airbnb
    url: root:123456@tcp(localhost:3306)/airbnb